import { Task } from "../types";

export const defaultTasks: Task[] = [
    {
        id: "1",
        columnId: "todo",
        content: "Install foundation for new building project",
        userName: "Saniyaa B Shetty",
        role: "Project Manager",
        userpfp: "./SaniyaaBShetty.png",
    },
    {
        id: "2",
        columnId: "doing",
        content: "Design layout for residential construction",
        userName: "Vedant Khade",
        role: "Architect",
        userpfp: "./VedantKhade.png",
    },
    {
        id: "3",
        columnId: "todo",
        content: "Procure materials for construction site",
        userName: "Vipul Mhatre",
        role: "Procurement Manager",
        userpfp: "./VipulMhatre.png",
    },
    {
        id: "4",
        columnId: "doing",
        content: "Construct brick walls for new project",
        userName: "Saniyaa B Shetty",
        role: "Project Manager",
        userpfp: "./SaniyaaBShetty.png",
    },
    {
        id: "5",
        columnId: "done",
        content: "Install electrical wiring in office building",
        userName: "Vedant Khade",
        role: "Architect",
        userpfp: "./VedantKhade.png",
    },
    {
        id: "6",
        columnId: "todo",
        content: "Prepare site for excavation and foundation work",
        userName: "Vipul Mhatre",
        role: "Procurement Manager",
        userpfp: "./VipulMhatre.png",
    },
    {
        id: "7",
        columnId: "done",
        content: "Complete plumbing work in residential project",
        userName: "Saniyaa B Shetty",
        role: "Project Manager",
        userpfp: "./SaniyaaBShetty.png",
    },
    {
        id: "8",
        columnId: "done",
        content: "Design layout for parking area",
        userName: "Vedant Khade",
        role: "Architect",
        userpfp: "./VedantKhade.png",
    },
    {
        id: "9",
        columnId: "todo",
        content: "Manage logistics for equipment transportation",
        userName: "Vipul Mhatre",
        role: "Procurement Manager",
        userpfp: "./VipulMhatre.png",
    },
    {
        id: "10",
        columnId: "todo",
        content: "Supervise site work for ongoing construction",
        userName: "Saniyaa B Shetty",
        role: "Project Manager",
        userpfp: "./SaniyaaBShetty.png",
    },
];
